apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: digital-wallet
build:
  artifacts:
  - image: digital-wallet-api
    context: digitalwallet-backend
  - image: digital-wallet-ui
    context: digitalwallet-frontend/digitalwalletapp
manifests:
  rawYaml:
  - deploy/db-manifest.yaml
  - deploy/backend-manifest.yaml
  - deploy/frontend-manifest.yaml
deploy:
  kubectl: {}