apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-frontend
  template:
    metadata:
      labels:
        app: wallet-frontend
    spec:
      containers:
      - name: frontend
        image: digital-wallet-ui # Skaffold bunu otomatik dolduracak
        ports:
        - containerPort: 80 # Nginx portu
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-frontend-svc
spec:
  type: LoadBalancer # Dışarıdan erişim için
  selector:
    app: wallet-frontend
  ports:
  - port: 80
    targetPort: 80